### ISSUE TITLE
Video stream does not close when finished

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#142]
Steps to reproduce:
- Open the sample encoder
- Register it in the system
- Select a file and start the encoder

- Open the sample decoder
- Register it in the system
- Start the decoder

- Open the admin panel
- Create a stream between the sample encoder and sample decoder
- Watch the stream until its conclusion

Expected result:
- The stream closes automatically

Actual result:
- The stream freezes on the last frame of the video and must be closed manually

**Comment by pobudzey** [comment]
For the -autoexit flag to work, ffplay needs to know the duration of the video it's displaying. This is why it works just fine when supplying a local file, but fails when supplying an SRT stream.

Marking this as "Won't fix" because we might not even encounter this issue when we start working with actual streams (webcam, screen share, etc)
