### ISSUE TITLE
Investigate SRT statistics

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#269]
As part of this task we should

* Determine what statistics can be obtained from an SRT stream
* Talk to the PM to determine which statistics are important / useful enough to show in the stream details page
* Determine if and how we can obtain these statistics from the `srt-live-transmit` tool.

**Comment by pobudzey** [comment]
SRT stream statistics can be obtained from srt-live-transmit by specifying the `-statsout` option, which outputs the following:
![image](https://user-images.githubusercontent.com/43392224/107259647-3f0e0500-6a0b-11eb-9e11-3c60e9d59945.png)

The output format of the statistics can be specified with `-pf:json`, which would output the report in json format like so:
![image](https://user-images.githubusercontent.com/43392224/107260057-b9d72000-6a0b-11eb-8b0c-5244eda8730c.png)

Additionally, we can specify the frequency of SRT statistics collection, based on the number of packets with `-s <number_of_packets>`. And finally, if we want a cumulative report instead of an incremental one, we can use the `-f` option for a full counter.

**Comment by pobudzey** [comment]
Copied my investigation report to our drive
