### ISSUE TITLE
Endpoint to get logs related to a stream

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#328]
Such logs include
- log that is created when the stream is started
- logs of devices reporting errors during the stream

**Comment by sebhani** [comment]
So far, we can decided that a log is stream related if serial_number field contains comma separated value (e.g. 123,420). I suggest creating another table called stream_logs which has an ISA relation with log_entity table since the relationship between these two entities is a covering one (meaning that a record can't be both in log_entity and in stream_logs). This would improve the query performance so much by not having to check all logs to extract the stream-related ones.

**Comment by felixlapierre** [comment]
Having them in a separate table is fine by me. However, keep in mind this endpoint needs us to retrieve the logs of a particular stream, not just retrieve all the logs associated to any stream.
